name: Build

on:
  push:
    branches:
      - turn-off-updates
  pull_request:
    branches:
      - turn-off-updates

permissions:
  contents: write

jobs:
  initialization:
    name: Initialization
    runs-on: windows-latest
    outputs:
      build_number: ${{ steps.build_number.outputs.build_number }}
    steps:
      - name: Generate Build Number
        id: build_number
        shell: pwsh
        run: |
          $date = (Get-Date).ToString("yyMMdd")
          $revision = "${{ github.run_number }}"
          $buildNumber = "$date$revision"
          echo "build_number=$buildNumber" >> $env:GITHUB_OUTPUT
          echo "Build Number: $buildNumber"

  code-format-validation:
    name: Code Format Validation
    runs-on: macos-latest
    needs: initialization
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-20.1.8/LLVM-20.1.8-macOS-ARM64.tar.xz
          tar -xf LLVM-20.1.8-macOS-ARM64.tar.xz
          sudo cp LLVM-20.1.8-macOS-ARM64/bin/clang-format* /usr/local/bin/
          rm -rf LLVM-20.1.8-macOS-ARM64*

      - name: Run clang-format
        run: |
          find . \( -name '*.h' -or -name '*.cpp' -or -name '*.c' -or -name '*.mm' -or -name '*.m' \) -print0 | xargs -0 clang-format -style=file -i
          git diff ${{ github.sha }}
          if [ "$(git diff ${{ github.sha }})" != "" ]; then exit 1; fi

  linux-deb-22:
    name: Linux Deb (Ubuntu 22.04 Qt5)
    runs-on: ubuntu-22.04
    needs: [initialization, code-format-validation]
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtchooser qtbase5-dev-tools qt5-qmake \
          qtbase5-dev qtmultimedia5-dev libpoppler-qt5-dev qttools5-dev-tools \
          libqt5opengl5-dev qtdeclarative5-dev libqt5svg5-dev qtquickcontrols2-5-dev \
          libunarr-dev dpkg-dev debhelper

      - name: Build
        run: |
          export DEFINES_VAR=DEFINES+=\"BUILD_NUMBER=\\\\\\\"${{ needs.initialization.outputs.build_number }}\\\\\\\"\"
          qmake CONFIG+="unarr" $DEFINES_VAR
          make

      - name: Create deb package
        run: |
          VERSION="$(cat common/yacreader_global.h | grep '#define VERSION "' | tr -d '#define VERSION' | tr -d '"' )"
          PKGVERSION="$VERSION-${{ needs.initialization.outputs.build_number }}"
          mkdir -p debian/tmp/usr/bin
          mkdir -p debian/tmp/usr/share/applications
          mkdir -p debian/tmp/usr/share/icons/hicolor/scalable/apps
          cp YACReader/YACReader debian/tmp/usr/bin/
          cp YACReaderLibrary/YACReaderLibrary debian/tmp/usr/bin/
          cp YACReaderLibraryServer/YACReaderLibraryServer debian/tmp/usr/bin/
          cp YACReader.desktop debian/tmp/usr/share/applications/
          cp YACReaderLibrary.desktop debian/tmp/usr/share/applications/
          cp YACReader.svg debian/tmp/usr/share/icons/hicolor/scalable/apps/
          cp YACReaderLibrary.svg debian/tmp/usr/share/icons/hicolor/scalable/apps/
          mkdir -p debian/tmp/DEBIAN
          cat > debian/tmp/DEBIAN/control << EOF
          Package: yacreader
          Version: $PKGVERSION
          Section: Graphics
          Priority: optional
          Architecture: amd64
          Depends: libqt5opengl5, libpoppler-qt5-1, libqt5quick5, libqt5quickwidgets5, libqt5quickcontrols2-5, libunarr1, qt5-image-formats-plugins
          Maintainer: YACReader
          Description: YACReader comic book reader
          EOF
          dpkg-deb --build debian/tmp 22deb_yacreader_${PKGVERSION}_amd64.deb

      - name: Upload deb package
        uses: actions/upload-artifact@v7
        with:
          name: linux-deb-22-${{ needs.initialization.outputs.build_number }}
          path: 22deb_yacreader*.deb

  linux-deb-24:
    name: Linux Deb (Ubuntu 24.04 Qt6)
    runs-on: ubuntu-24.04
    needs: [initialization, code-format-validation]
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtchooser qt6-tools-dev qt6-base-dev-tools qmake6 qmake6-bin \
          qt6-base-dev qt6-multimedia-dev qt6-tools-dev-tools libgl-dev qt6-l10n-tools \
          libqt6opengl6-dev qt6-declarative-dev libqt6svg6-dev libqt6core5compat6-dev libpoppler-qt6-dev \
          libunarr-dev dpkg-dev debhelper

      - name: Build
        run: |
          qtchooser -list-versions
          export DEFINES_VAR=DEFINES+=\"BUILD_NUMBER=\\\\\\\"${{ needs.initialization.outputs.build_number }}\\\\\\\"\"
          qmake6 CONFIG+="unarr" $DEFINES_VAR
          qmake6 -v
          make

      - name: Create deb package
        run: |
          VERSION="$(cat common/yacreader_global.h | grep '#define VERSION "' | tr -d '#define VERSION' | tr -d '"' )"
          PKGVERSION="$VERSION-${{ needs.initialization.outputs.build_number }}"
          mkdir -p debian/tmp/usr/bin
          mkdir -p debian/tmp/usr/share/applications
          mkdir -p debian/tmp/usr/share/icons/hicolor/scalable/apps
          cp YACReader/YACReader debian/tmp/usr/bin/
          cp YACReaderLibrary/YACReaderLibrary debian/tmp/usr/bin/
          cp YACReaderLibraryServer/YACReaderLibraryServer debian/tmp/usr/bin/
          cp YACReader.desktop debian/tmp/usr/share/applications/
          cp YACReaderLibrary.desktop debian/tmp/usr/share/applications/
          cp YACReader.svg debian/tmp/usr/share/icons/hicolor/scalable/apps/
          cp YACReaderLibrary.svg debian/tmp/usr/share/icons/hicolor/scalable/apps/
          mkdir -p debian/tmp/DEBIAN
          cat > debian/tmp/DEBIAN/control << EOF
          Package: yacreader
          Version: $PKGVERSION
          Section: Graphics
          Priority: optional
          Architecture: amd64
          Depends: libqt6opengl6, libpoppler-qt6-3, libqt6multimedia6, libqt6core5compat6, libqt6svg6, qt6-declarative-dev, qml6-module-qt5compat-graphicaleffects, qml6-module-qtquick-templates, libunarr1, qt6-image-formats-plugins
          Maintainer: YACReader
          Description: YACReader comic book reader
          EOF
          dpkg-deb --build debian/tmp 24deb_yacreader_${PKGVERSION}_amd64.deb

      - name: Upload deb package
        uses: actions/upload-artifact@v7
        with:
          name: linux-deb-24-${{ needs.initialization.outputs.build_number }}
          path: 24deb_yacreader*.deb

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [initialization, linux-deb-22, linux-deb-24]
    if: github.event_name == 'push'
    steps:
      - name: Download Ubuntu 22.04 deb
        uses: actions/download-artifact@v8
        with:
          name: linux-deb-22-${{ needs.initialization.outputs.build_number }}
          path: debs

      - name: Download Ubuntu 24.04 deb
        uses: actions/download-artifact@v8
        with:
          name: linux-deb-24-${{ needs.initialization.outputs.build_number }}
          path: debs

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.initialization.outputs.build_number }}
          body: "YACReader ${{ needs.initialization.outputs.build_number }}"
          draft: false
          prerelease: false
          files: debs/*.deb
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_PAT }}
